# Generated by Django 4.2.3 on 2023-07-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('by', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField(blank=True, default='')),
                ('articlePageImage', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('articlePageContent', models.TextField(blank=True, default='')),
                ('articlePageImage2', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('articlePageContent2', models.TextField(blank=True, default='')),
                ('articlePageImage3', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('articlePageContent3', models.TextField(blank=True, default='')),
            ],
        ),
    ]
